import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { loadCatalog, sqlNumber, sqlText } from "./lib/okf-catalog.mjs";

const { catalog, sha256 } = await loadCatalog();
const outputDir = join(process.cwd(), "generated");
const outputPath = join(outputDir, "okf-projection.sql");

const lines = [
  "-- Generated by scripts/project-okf.mjs. Do not edit manually.",
  `-- Catalog SHA-256: ${sha256}`,
  "PRAGMA defer_foreign_keys = true;",
  "",
];

for (const site of catalog.sites) {
  lines.push(`INSERT INTO sites (id, name_ar, name_en, city, category, description_ar, description_en, latitude, longitude, last_verified)
VALUES (${sqlText(site.id)}, ${sqlText(site.nameAr)}, ${sqlText(site.nameEn)}, ${sqlText(site.city)}, ${sqlText(site.category)}, ${sqlText(site.descriptionAr)}, ${sqlText(site.descriptionEn)}, ${sqlNumber(site.latitude)}, ${sqlNumber(site.longitude)}, ${sqlText(site.lastVerified)})
ON CONFLICT(id) DO UPDATE SET name_ar=excluded.name_ar, name_en=excluded.name_en, city=excluded.city, category=excluded.category, description_ar=excluded.description_ar, description_en=excluded.description_en, latitude=excluded.latitude, longitude=excluded.longitude, last_verified=excluded.last_verified;\n`);
}

for (const source of catalog.sources) {
  lines.push(`INSERT INTO sources (id, site_id, title, url, source_type, description_ar, description_en, authority, last_verified)
VALUES (${sqlText(source.id)}, ${sqlText(source.siteId)}, ${sqlText(source.title)}, ${sqlText(source.url)}, ${sqlText(source.sourceType)}, ${sqlText(source.descriptionAr)}, ${sqlText(source.descriptionEn)}, ${sqlText(source.authority)}, ${sqlText(source.lastVerified)})
ON CONFLICT(id) DO UPDATE SET site_id=excluded.site_id, title=excluded.title, url=excluded.url, source_type=excluded.source_type, description_ar=excluded.description_ar, description_en=excluded.description_en, authority=excluded.authority, last_verified=excluded.last_verified;\n`);
}

for (const site of catalog.sites) {
  lines.push(`DELETE FROM site_aliases WHERE site_id=${sqlText(site.id)};`);
  for (const [language, aliases] of Object.entries(site.aliases)) {
    for (const alias of aliases) {
      lines.push(`INSERT INTO site_aliases (site_id, alias, language, alias_type) VALUES (${sqlText(site.id)}, ${sqlText(alias)}, ${sqlText(language)}, 'name');`);
    }
  }
  lines.push("");
}

for (const claim of catalog.claims) {
  for (const [language, text] of [["ar", claim.textAr], ["en", claim.textEn]]) {
    const id = `${claim.id}.${language}`;
    lines.push(`INSERT INTO knowledge_claims (id, site_id, source_id, language, claim_type, claim_text, verified, last_verified, updated_at)
VALUES (${sqlText(id)}, ${sqlText(claim.siteId)}, ${sqlText(claim.sourceId)}, ${sqlText(language)}, ${sqlText(claim.claimType)}, ${sqlText(text)}, 1, ${sqlText(claim.lastVerified)}, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET site_id=excluded.site_id, source_id=excluded.source_id, language=excluded.language, claim_type=excluded.claim_type, claim_text=excluded.claim_text, verified=excluded.verified, last_verified=excluded.last_verified, updated_at=CURRENT_TIMESTAMP;`);
  }
}

for (const media of catalog.media) {
  lines.push(`INSERT INTO media_assets (id, site_id, source_id, url, title_ar, title_en, alt_ar, alt_en, source_title_ar, source_title_en, source_url, rights_holder, rights_url, last_verified)
VALUES (${sqlText(media.id)}, ${sqlText(media.siteId)}, ${sqlText(media.sourceId)}, ${sqlText(media.url)}, ${sqlText(media.titleAr)}, ${sqlText(media.titleEn)}, ${sqlText(media.altAr)}, ${sqlText(media.altEn)}, ${sqlText(media.sourceTitleAr)}, ${sqlText(media.sourceTitleEn)}, ${sqlText(media.sourceUrl)}, ${sqlText(media.rightsHolder)}, ${sqlText(media.rightsUrl)}, ${sqlText(media.lastVerified)})
ON CONFLICT(id) DO UPDATE SET site_id=excluded.site_id, source_id=excluded.source_id, url=excluded.url, title_ar=excluded.title_ar, title_en=excluded.title_en, alt_ar=excluded.alt_ar, alt_en=excluded.alt_en, source_title_ar=excluded.source_title_ar, source_title_en=excluded.source_title_en, source_url=excluded.source_url, rights_holder=excluded.rights_holder, rights_url=excluded.rights_url, last_verified=excluded.last_verified;\n`);
}

lines.push(`DELETE FROM heritage_search;
INSERT INTO heritage_search (source_id, site_id, name_ar, name_en, city, category, site_description_ar, source_title, source_description_ar, source_description_en, aliases)
SELECT s.id, st.id, st.name_ar, COALESCE(st.name_en, ''), COALESCE(st.city, ''), COALESCE(st.category, ''), COALESCE(st.description_ar, ''), s.title, COALESCE(s.description_ar, ''), COALESCE(s.description_en, ''), COALESCE((SELECT group_concat(sa.alias, ' ') FROM site_aliases sa WHERE sa.site_id=st.id), '')
FROM sources s JOIN sites st ON st.id=s.site_id;\n`);

const expandedClaimCount = catalog.claims.length * 2;
lines.push(`INSERT OR IGNORE INTO knowledge_projection_runs (id, catalog_sha256, catalog_revision, site_count, source_count, claim_count, media_count)
VALUES (${sqlText(`projection.${sha256.slice(0, 16)}`)}, ${sqlText(sha256)}, ${sqlText(catalog.revision)}, ${catalog.sites.length}, ${catalog.sources.length}, ${expandedClaimCount}, ${catalog.media.length});`);

await mkdir(outputDir, { recursive: true });
await writeFile(outputPath, `${lines.join("\n")}\n`, "utf8");
console.log(`Projected ${catalog.sites.length} sites, ${catalog.sources.length} sources, ${expandedClaimCount} claims, and ${catalog.media.length} media records.`);
console.log(`Wrote ${outputPath}`);
